// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20220314095243_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Programming",
                            Url = "web-programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Software Engineering",
                            Url = "software-engineering"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Databases",
                            Url = "databases"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Access detailed content and examples on Azure SQL, a set of cloud services that allows for SQL Server to be deployed in the cloud. This book teaches the fundamentals of deployment, configuration, security, performance, and availability of Azure SQL from the perspective of these same tasks and capabilities in SQL Server.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-5931-3",
                            Price = 26.99m,
                            Title = "Azure SQL Revealed"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Professional developers get ready to produce leaner applications for the ASP.NET Core platform. This edition puts ASP.NET Core 3 into context, and takes a deep dive into the tools and techniques required to build modern, extensible web applications.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-5440-0",
                            Price = 49.99m,
                            Title = "Pro ASP.NET Core 3"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Implement design patterns in .NET using the latest versions of the C# and F# languages. This book provides a comprehensive overview of the field of design patterns as they are used in today’s developer toolbox.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-4366-4",
                            Price = 29.99m,
                            Title = "Design Patterns in .NET"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Welcome to this one-stop-shop for learning Angular. Pro Angular is the most concise and comprehensive guide available, giving you the knowledge you need to take full advantage of this popular framework for building your own dynamic JavaScript applications.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-5998-6",
                            Price = 49.99m,
                            Title = "Pro Angular 9"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Explore data structures and algorithm concepts and their relation to everyday JavaScript development. A basic understanding of these ideas is essential to any JavaScript developer wishing to analyze and build great software solutions.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-3988-9",
                            Price = 29.99m,
                            Title = "JavaScript Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Write optimized queries. This book helps you write queries that perform fast and deliver results on time. You will learn that query optimization is not a dark art practiced by a small, secretive cabal of sorcerers. Any motivated professional can learn to write efficient queries from the get-go and capably optimize existing queries. You will learn to look at the process of writing a query from the database engine’s point of view, and know how to think like the database optimizer.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-6885-8",
                            Price = 36.99m,
                            Title = "PostgreSQL Query Optimization"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Use this fast and complete guide to optimize the performance of MongoDB databases and the applications that depend on them. You will be able to turbo-charge the performance of your MongoDB applications to provide a better experience for your users, reduce your running costs, and avoid application growing pains. MongoDB is the world’s most popular document database and the foundation for thousands of mission-critical applications.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-6879-7",
                            Price = 29.99m,
                            Title = "MongoDB Performance Tuning"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Agile Visualization with Pharo focuses on the Roassal visualization engine and first presents the basic and necessary tools to visualize data, including an introduction to the Pharo programming language. Once you’ve grasped the basics, you’ll learn all about the development environment offered by Roassal. The book provides numerous ready-to-use examples.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-7161-2",
                            Price = 26.99m,
                            Title = "Agile Visualization with Pharo"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Programming Algorithms in Lisp shows real-world engineering considerations and constraints that influence the programs that use these algorithms. It includes practical use cases of the applications of the algorithms to a variety of real-world problems.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-6428-7",
                            Price = 22.99m,
                            Title = "Programming Algorithms in Lisp"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Learn to leverage the power of Svelte to produce web applications that are efficient and fast. This project-oriented book simplifies creating sites using Svelte from start to finish, with little more than a text editor and familiar languages such as HTML, CSS, and JavaScript. It equips you with a starting toolset that you can use to develop future projects, incorporate into your existing workflow, and allow you to take your websites to the next level.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-7374-6",
                            Price = 35.99m,
                            Title = "Practical Svelte"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Quickly discover solutions to common problems, best practices you can follow, and everything jQuery has to offer. Using a problem-solution approach, this book begins with small initial problems that developers typically face while working with jQuery, and gradually goes deeper to explore more complex problems. The solutions include illustrations and clear, concise explanations of the code.",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-7304-3",
                            Price = 15.99m,
                            Title = "jQuery Recipes"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Make your websites more dynamic by adding a feedback form, creating a private area where members can upload images that are automatically resized, or storing all your content in a database. David Powers has updated his definitive book to incorporate the latest techniques and changes to PHP with the arrival of PHP 8. New features include named attributes, constructor property promotion, the stricter and more concise match expression, union types, and more.​",
                            ImageUrl = "https://media.springernature.com/w306/springer-static/cover-hires/book/978-1-4842-7141-4",
                            Price = 39.99m,
                            Title = "PHP 8 Solutions"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorEcommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
