// <auto-generated />
using System;
using AlvinLaulana.HrApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlvinLaulana.HrApp.DataAccess.Migrations
{
    [DbContext(typeof(HrDbContext))]
    partial class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlvinLaulana.HrApp.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "John Doe",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Jane Smith",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Alice Johnson",
                            PhoneNumber = "5551234567"
                        },
                        new
                        {
                            Id = 7,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Bob Brown",
                            PhoneNumber = "4449876543"
                        },
                        new
                        {
                            Id = 11,
                            Age = 28,
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Charlie Davis",
                            PhoneNumber = "3334567890"
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Diana Evans",
                            PhoneNumber = "2223456789"
                        },
                        new
                        {
                            Id = 6,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Ethan Green",
                            PhoneNumber = "1112345678"
                        },
                        new
                        {
                            Id = 5,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Fiona Harris",
                            PhoneNumber = "6661234567"
                        },
                        new
                        {
                            Id = 8,
                            Age = 34,
                            DateOfBirth = new DateTime(1989, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "George King",
                            PhoneNumber = "7779876543"
                        },
                        new
                        {
                            Id = 9,
                            Age = 29,
                            DateOfBirth = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Hannah Lee",
                            PhoneNumber = "8884567890"
                        },
                        new
                        {
                            Id = 12,
                            Age = 32,
                            DateOfBirth = new DateTime(1990, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Ian Miller",
                            PhoneNumber = "9993456789"
                        },
                        new
                        {
                            Id = 10,
                            Age = 37,
                            DateOfBirth = new DateTime(1986, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Julia Nelson",
                            PhoneNumber = "0002345678"
                        },
                        new
                        {
                            Id = 13,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Kevin Ortiz",
                            PhoneNumber = "1111234567"
                        },
                        new
                        {
                            Id = 14,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Laura Perez",
                            PhoneNumber = "2229876543"
                        },
                        new
                        {
                            Id = 15,
                            Age = 28,
                            DateOfBirth = new DateTime(1995, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Michael Roberts",
                            PhoneNumber = "3334567890"
                        },
                        new
                        {
                            Id = 16,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Nina Scott",
                            PhoneNumber = "4443456789"
                        },
                        new
                        {
                            Id = 17,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Oscar Taylor",
                            PhoneNumber = "5552345678"
                        },
                        new
                        {
                            Id = 18,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Paula White",
                            PhoneNumber = "6661234567"
                        },
                        new
                        {
                            Id = 19,
                            Age = 34,
                            DateOfBirth = new DateTime(1989, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Quentin Young",
                            PhoneNumber = "7779876543"
                        },
                        new
                        {
                            Id = 20,
                            Age = 29,
                            DateOfBirth = new DateTime(1994, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Rachel Adams",
                            PhoneNumber = "8884567890"
                        },
                        new
                        {
                            Id = 21,
                            Age = 32,
                            DateOfBirth = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Steve Baker",
                            PhoneNumber = "9993456789"
                        },
                        new
                        {
                            Id = 22,
                            Age = 37,
                            DateOfBirth = new DateTime(1986, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Tina Clark",
                            PhoneNumber = "0002345678"
                        },
                        new
                        {
                            Id = 23,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Ursula Diaz",
                            PhoneNumber = "1111234567"
                        },
                        new
                        {
                            Id = 24,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Victor Evans",
                            PhoneNumber = "2229876543"
                        },
                        new
                        {
                            Id = 25,
                            Age = 28,
                            DateOfBirth = new DateTime(1995, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Wendy Foster",
                            PhoneNumber = "3334567890"
                        },
                        new
                        {
                            Id = 26,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Xander Garcia",
                            PhoneNumber = "4443456789"
                        },
                        new
                        {
                            Id = 27,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Yara Harris",
                            PhoneNumber = "5552345678"
                        },
                        new
                        {
                            Id = 28,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Zachary Johnson",
                            PhoneNumber = "6661234567"
                        },
                        new
                        {
                            Id = 29,
                            Age = 34,
                            DateOfBirth = new DateTime(1989, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Alice Smith",
                            PhoneNumber = "7779876543"
                        },
                        new
                        {
                            Id = 30,
                            Age = 29,
                            DateOfBirth = new DateTime(1994, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Bob Johnson",
                            PhoneNumber = "8884567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
